services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hiking_db
    ports:
      - "4040:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  backend:
    build:
      context: ./backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=hiking_db
    ports:
      - "5001:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/data
    command: >
      bash -c "python /app/insert_data.py && flask run --host=0.0.0.0"  # Run insert_data.py before starting Flask
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
