version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hiking_trails
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file
    ports:
      - "4040:3306"
      
  backend:
    build:
      context: ./backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:password@db/hiking_trails
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./data:/app/data  # Mount the data folder from the host to /app/data in the container
    # Add command to run insert_data.py after the container starts
    command: ["sh", "-c", "python /app/insert_data.py && flask run --host=0.0.0.0"]

volumes:
  db_data:
